apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ga2j5xbrz-nodejs 
  janus-idp.io/tekton: ga2j5xbrz-nodejs
  backstage.io/kubernetes-id: ga2j5xbrz-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ga2j5xbrz-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml