apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ga2j5xbrz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ga2j5xbrz-nodejs 
  name: ga2j5xbrz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ga2j5xbrz-nodejs 
